// Generated by CoffeeScript 1.10.0
(function() {
  this.Vector = (function() {
    Vector.x = 0;

    Vector.y = 0;

    function Vector(x, y) {
      this.x = x;
      this.y = y;
    }

    Vector.prototype.magnitude = function() {
      return Math.sqrt(Math.pow(this.x, 2) + Math.pow(this.y, 2));
    };

    Vector.prototype.normalize = function() {
      return this.divide_num(this.magnitude());
    };

    Vector.prototype.subtract = function(other) {
      var vec;
      vec = new Vector(0, 0);
      vec.x = this.x - other.x;
      vec.y = this.y - other.y;
      return vec;
    };

    Vector.prototype.add = function(other) {
      var vec;
      vec = new Vector(0, 0);
      vec.x = this.x - other.x;
      vec.y = this.y - other.y;
      return vec;
    };

    Vector.prototype.divide_num = function(other) {
      var vec;
      vec = new Vector(this.x, this.y);
      vec.x /= other;
      vec.y /= other;
      return vec;
    };

    Vector.prototype.mult_num = function(other) {
      var vec;
      vec = new Vector(this.x, this.y);
      vec.x *= other;
      vec.y *= other;
      return vec;
    };

    return Vector;

  })();

  this.Box = (function() {
    Box.name = '';

    Box.text = '42';

    Box.compText = '';

    Box.boxID = 0;

    function Box(type) {
      this.type = type;
      switch (type) {
        case cmdName:
          this.entryPoints = cmdEntries;
          break;
        case evalName:
          this.entryPoints = evalEntries;
          break;
        case interName:
          this.entryPoints = interEntries;
          break;
        case 'start':
          this.entryPoints = cmdEntries;
          break;
        case 'end':
          this.entryPoints = cmdEntries;
      }
      this.prevBoxes = [];
      this.yesBox = null;
      this.noBox = null;
      this.position = new Vector(0, 0);
    }

    Box.prototype.setText = function(text) {
      this.text = text;
      return this.compText = compile(text, this.type);
    };

    Box.prototype.copy = function() {
      var copied;
      copied = new Box(this.type);
      copied.name = this.name;
      copied.text = this.text;
      copied.compText = this.compText;
      copied.boxID = this.boxID;
      copied.prevBoxes = this.prevBoxes;
      copied.yesBox = this.yesBox;
      copied.noBox = this.noBox;
      copied.position = new Vector(0, 0);
      copied.position.x = this.position.x;
      copied.position.y = this.position.y;
      return copied;
    };

    return Box;

  })();

  this.boxes = [];

  this.InitForms = function() {
    var endingBox, startingBox;
    startingBox = new Box('start');
    endingBox = new Box('end');
    startingBox.boxID = 0;
    startingBox.position.x = 520;
    startingBox.position.y = 208;
    startingBox.name = 'Start';
    startingBox.text = 'Start';
    endingBox.boxID = 1;
    endingBox.position.x = 520;
    endingBox.position.y = 416;
    endingBox.name = 'End';
    endingBox.text = 'End';
    this.init_boxes = [startingBox, endingBox];
    return this.boxes = init_boxes;
  };

  this.CopyBoxes = function(boxes) {
    var box, cboxes, j, len;
    if (boxes == null) {
      boxes = this.boxes;
    }
    cboxes = [];
    for (j = 0, len = boxes.length; j < len; j++) {
      box = boxes[j];
      cboxes.push(box.copy());
    }
    return cboxes;
  };

  this.GetBoxByCoords = function(x, y, boxes) {
    var box, j, len;
    if (boxes == null) {
      boxes = this.boxes;
    }
    for (j = 0, len = boxes.length; j < len; j++) {
      box = boxes[j];
      if (box.position.x === x && box.position.y === y) {
        return box;
      }
    }
    return false;
  };

  this.DeleteBoxByID = function(id, boxes) {
    var i, j, ref;
    if (boxes == null) {
      boxes = this.boxes;
    }
    for (i = j = 0, ref = boxes.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      if (boxes[i].boxID === id) {
        boxes.splice(i, 1);
        return;
      }
    }
  };

  this.GetByID = function(id, boxes) {
    var i, j, ref;
    if (boxes == null) {
      boxes = this.boxes;
    }
    for (i = j = 0, ref = boxes.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      if (boxes[i].boxID === id) {
        return boxes[i];
      }
    }
  };

}).call(this);
