// Generated by CoffeeScript 1.10.0
(function() {
  var DisableAll, DrawNexts, DrawSelections, HTML_SetAttributes, HTML_els, HideAllEl, ShowAllEl, clickAction, isMouseDown, lastID, loadClick, moveName, selNoName, selYesName, selectName;

  HTML_els = (function() {
    function HTML_els() {}

    HTML_els.propClass = 'prop';

    HTML_els.genPropID = 'generalProp';

    HTML_els.nameID = 'nameInput';

    HTML_els.commandID = 'cmdInput';

    HTML_els.nextPropID = 'nextProp';

    HTML_els.delNextID = 'delNext';

    HTML_els.nextYesPropID = 'nextYesProp';

    HTML_els.delYesID = 'delYes';

    HTML_els.nextNoPropID = 'nextNoProp';

    HTML_els.delNoID = 'delNo';

    HTML_els.cmdPropID = 'cmdProp';

    HTML_els.evalPropID = 'evalProp';

    HTML_els.interPropID = 'interProp';

    HTML_els.interCmdID = 'interCmdProp';

    return HTML_els;

  })();

  selectName = 'sel';

  selYesName = 'selYes';

  selNoName = 'selNo';

  moveName = 'move';

  clickAction = '';

  this.selectedBox = null;

  lastID = 2;

  this.InitHTML = function() {
    HTML_els.curModeEl = document.getElementById('curMode');
    HTML_els.propEl = document.getElementsByClassName(HTML_els.propClass);
    HTML_els.genPropEl = document.getElementsByClassName(HTML_els.genPropID);
    HTML_els.nameEl = document.getElementById(HTML_els.nameID);
    HTML_els.commandEl = document.getElementById(HTML_els.commandID);
    HTML_els.nextPropEl = document.getElementById(HTML_els.nextPropID);
    HTML_els.delNextEl = document.getElementById(HTML_els.delNextID);
    HTML_els.YesPropEl = document.getElementById(HTML_els.nextYesPropID);
    HTML_els.delYesEl = document.getElementById(HTML_els.delYesID);
    HTML_els.NoPropEl = document.getElementById(HTML_els.nextNoPropID);
    HTML_els.delNoEl = document.getElementById(HTML_els.delNoID);
    HTML_els.cmdPropEl = document.getElementById(HTML_els.cmdPropID);
    HTML_els.evalPropEl = document.getElementById(HTML_els.evalPropID);
    HTML_els.interPropEl = document.getElementById(HTML_els.interPropID);
    HTML_els.interCmdEl = document.getElementById(HTML_els.interCmdID);
    document.getElementById('diagr').onselectstart = function() {
      return false;
    };
    document.getElementById('diagr').onmousemove = CanvasDrag;
    document.getElementById('diagr').onmouseup = CanvasUp;
    return document.onmouseup = DocumentUp;
  };

  this.SaveDia = function() {
    var text;
    text = saveString();
    return swal({
      title: "Here is your save",
      html: "<span>(double click to copy)</span><br><br><textarea rows=20 cols=50 readonly=true style=\"resize:none\">" + text + "</textarea>"
    });
  };

  this.LoadDia = function() {
    return swal({
      title: "Input save file",
      input: 'text',
      inputPlaceholder: "Your input here"
    }).then(loadClick);
  };

  loadClick = function(text) {
    if (text !== "") {
      loadString(text);
      return RestoreCtx();
    }
  };

  this.RunDia = function() {
    this.IntWorker.postMessage(['eraseVars']);
    return this.IntWorker.postMessage(['interprete', this.boxes[0]]);
  };

  this.StopDia = function() {
    return this.IntWorker.postMessage(['stop']);
  };

  this.SelectType = function(type) {
    switch (type) {
      case 'cmd':
        clickAction = cmdName;
        return HTML_els.curModeEl.innerHTML = "Add Command";
      case 'eval':
        clickAction = evalName;
        return HTML_els.curModeEl.innerHTML = "Add Evaluation";
      case 'inter':
        clickAction = interName;
        return HTML_els.curModeEl.innerHTML = "Add Interface";
      case 'selYes':
        clickAction = selYesName;
        if (this.selectedBox.type === cmdName || this.selectedBox.type === interName) {
          return HTML_els.curModeEl.innerHTML = "Select Next Box";
        } else {
          return HTML_els.curModeEl.innerHTML = "Select Yes Box";
        }
        break;
      case 'selNo':
        clickAction = selNoName;
        return HTML_els.curModeEl.innerHTML = "Select No Box";
      case 'move':
        clickAction = moveName;
        return HTML_els.curModeEl.innerHTML = "Move Box";
    }
  };

  this.DeleteNext = function(type) {
    if (type === 'yes') {
      this.selectedBox.yesBox = null;
    } else {
      this.selectedBox.noBox = null;
    }
    SetSelectionGUI(this.selectedBox);
    RestoreCtx();
    return DrawSelections();
  };

  this.OnNameChange = function(text) {
    return this.selectedBox.name = text;
  };

  this.OnCommandChange = function(text) {
    this.selectedBox.setText(text);
    RestoreCtx();
    return DrawSelections();
  };

  this.DeleteSelBox = function() {
    var i, j, k, l, prevBox, ref, ref1, ref2;
    DeleteBoxByID(this.selectedBox.boxID);
    if (this.selectedBox.prevBoxes.length > 0) {
      for (i = j = 0, ref = this.selectedBox.prevBoxes.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        prevBox = this.selectedBox.prevBoxes[i];
        if (prevBox.yesBox) {
          if (prevBox.yesBox.boxID === this.selectedBox.boxID) {
            this.selectedBox.prevBoxes[i].yesBox = null;
          } else {
            this.selectedBox.prevBoxes[i].noBox = null;
          }
        } else {
          this.selectedBox.prevBoxes[i].noBox = null;
        }
      }
    }
    if (this.selectedBox.yesBox) {
      for (i = k = 0, ref1 = this.selectedBox.yesBox.prevBoxes.length; 0 <= ref1 ? k < ref1 : k > ref1; i = 0 <= ref1 ? ++k : --k) {
        prevBox = this.selectedBox.yesBox.prevBoxes[i];
        if (prevBox.boxID === this.selectedBox.boxID) {
          this.selectedBox.yesBox.prevBoxes.splice(i, 1);
        }
      }
    }
    if (this.selectedBox.noBox) {
      for (i = l = 0, ref2 = this.selectedBox.noBox.prevBoxes.lenght; 0 <= ref2 ? l < ref2 : l > ref2; i = 0 <= ref2 ? ++l : --l) {
        prevBox = this.selectedBox.noBox.prevBoxes[i];
        if (prevBox.boxID === this.selectedBox.boxID) {
          this.selectedBox.noBox.prevBoxes.splice(i, 1);
        }
      }
    }
    this.selectedBox = null;
    clickAction = selectName;
    SelectType(clickAction);
    HideAllEl(HTML_els.propEl);
    HideAllEl(HTML_els.genPropEl);
    DisableAll();
    return RestoreCtx();
  };

  DisableAll = function() {
    HTML_els.cmdPropEl.setAttribute('hidden', '');
    HTML_els.evalPropEl.setAttribute('hidden', '');
    HTML_els.interPropEl.setAttribute('hidden', '');
    return HTML_els.interCmdEl.setAttribute('hidden', '');
  };

  HideAllEl = function(el_arr) {
    var i, j, ref, results;
    results = [];
    for (i = j = 0, ref = el_arr.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      results.push(el_arr[i].setAttribute('hidden', ''));
    }
    return results;
  };

  ShowAllEl = function(el_arr) {
    var i, j, ref, results;
    results = [];
    for (i = j = 0, ref = el_arr.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
      results.push(el_arr[i].removeAttribute('hidden'));
    }
    return results;
  };

  HTML_SetAttributes = function(box) {
    HTML_els.curModeEl.innerHTML = "Selecting";
    if (box.type === 'start' || box.type === 'end') {
      HideAllEl(HTML_els.propEl);
    } else {
      ShowAllEl(HTML_els.propEl);
      HTML_els.nameEl.value = box.name;
      HTML_els.commandEl.value = box.text;
    }
    ShowAllEl(HTML_els.genPropEl);
    DisableAll();
    if (box.type === cmdName) {
      HTML_els.cmdPropEl.removeAttribute('hidden');
      return HTML_els.interCmdEl.removeAttribute('hidden');
    } else if (box.type === interName) {
      HTML_els.interPropEl.removeAttribute('hidden');
      return HTML_els.interCmdEl.removeAttribute('hidden');
    } else if (box.type === evalName) {
      return HTML_els.evalPropEl.removeAttribute('hidden');
    } else if (box.type === 'start') {
      return HTML_els.interCmdEl.removeAttribute('hidden');
    }
  };

  this.SetSelectionGUI = function(box) {
    if (box.type === cmdName || box.type === interName || box.type === 'start') {
      if (box.yesBox) {
        HTML_els.nextPropEl.innerHTML = box.yesBox.name;
        return HTML_els.delNextEl.removeAttribute('hidden');
      } else {
        HTML_els.nextPropEl.innerHTML = '...';
        return HTML_els.delNextEl.setAttribute('hidden', '');
      }
    } else {
      if (box.yesBox) {
        HTML_els.YesPropEl.innerHTML = box.yesBox.name;
        HTML_els.delYesEl.removeAttribute('hidden');
      } else {
        HTML_els.YesPropEl.innerHTML = '...';
        HTML_els.delYesEl.setAttribute('hidden', '');
      }
      if (box.noBox) {
        HTML_els.NoPropEl.innerHTML = box.noBox.name;
        return HTML_els.delNoEl.removeAttribute('hidden');
      } else {
        HTML_els.NoPropEl.innerHTML = '...';
        return HTML_els.delNoEl.setAttribute('hidden', '');
      }
    }
  };

  isMouseDown = false;

  this.CanvasUp = function(event) {
    return isMouseDown = false;
  };

  this.DocumentUp = function(event) {
    return isMouseDown = false;
  };

  this.CanvasDrag = function(event) {
    var gx, gy, overingCell, x, y;
    if (selectedBox && isMouseDown) {
      console.log("Moving");
      x = event.offsetX;
      y = event.offsetY;
      gx = Math.round(x / (boxSize[0] + gridDist)) * (boxSize[0] + gridDist);
      gy = Math.round(y / (boxSize[1] + gridDist)) * (boxSize[1] + gridDist);
      overingCell = GetBoxByCoords(gx, gy);
      if (!overingCell) {
        selectedBox.position.x = gx;
        selectedBox.position.y = gy;
        RestoreCtx();
        return DrawSelections();
      }
    }
  };

  this.CanvasClick = function(event) {
    var clickedCell, gx, gy, newBox, x, y;
    isMouseDown = true;
    console.log("Down!");
    x = event.offsetX;
    y = event.offsetY;
    gx = Math.round(x / (boxSize[0] + gridDist)) * (boxSize[0] + gridDist);
    gy = Math.round(y / (boxSize[1] + gridDist)) * (boxSize[1] + gridDist);
    clickedCell = GetBoxByCoords(gx, gy);
    if (clickAction === selYesName || clickAction === selNoName) {
      if (clickedCell) {
        if (this.selectedBox !== clickedCell && clickedCell.type !== 'start') {
          if (clickAction === selYesName) {
            if (this.selectedBox.yesBox !== clickedCell) {
              this.selectedBox.yesBox = clickedCell;
              this.selectedBox.yesBox.prevBoxes.push(this.selectedBox);
            }
          } else {
            if (this.selectedBox.noBox !== clickedCell) {
              this.selectedBox.noBox = clickedCell;
              this.selectedBox.noBox.prevBoxes.push(this.selectedBox);
            }
          }
          RestoreCtx();
          DrawSelections();
          SetSelectionGUI(this.selectedBox);
        } else {
          HTML_els.curModeEl.innerHTML = 'Selecting';
          swal('Cannot set next as itself or start!');
        }
      }
      clickAction = selectName;
      HTML_els.curModeEl.innerHTML = 'Selecting';
      return;
    } else if (clickAction === cmdName || clickAction === evalName || clickAction === interName) {
      if (!clickedCell) {
        newBox = new Box(clickAction + "");
        newBox.position = new Vector(gx, gy);
        newBox.name = clickAction + lastID.toString();
        if (newBox.type !== interName) {
          newBox.setText('"Input command"');
        } else {
          newBox.setText('output("Hello!")');
        }
        newBox.boxID = lastID;
        lastID += 1;
        this.boxes.push(newBox);
        clickedCell = newBox;
        DrawBox(gx, gy);
      } else {
        swal('Position already occupied');
      }
    } else if (clickAction === moveName) {
      if (!clickedCell) {
        this.selectedBox.position.x = gx;
        this.selectedBox.position.y = gy;
        RestoreCtx();
        DrawSelections();
      } else {
        swal('Position already occupied');
      }
      clickAction = selectName;
      HTML_els.curModeEl.innerHTML = "Selecting";
      return;
    }
    clickAction = selectName;
    console.log(clickedCell);
    if (clickedCell) {
      RestoreCtx();
      this.selectedBox = clickedCell;
      HTML_SetAttributes(this.selectedBox);
      SetSelectionGUI(this.selectedBox);
      DrawSelections();
    } else {
      this.selectedBox = null;
      RestoreCtx();
      HideAllEl(HTML_els.propEl);
      HideAllEl(HTML_els.genPropEl);
      DisableAll();
    }
  };

  DrawSelections = function() {
    DrawSelection(this.selectedBox.position.x, this.selectedBox.position.y);
    return DrawNexts();
  };

  DrawNexts = function() {
    if (this.selectedBox.yesBox) {
      DrawSelection(this.selectedBox.yesBox.position.x, this.selectedBox.yesBox.position.y, "green");
      DrawConnection(this.selectedBox, this.selectedBox.yesBox, "green");
    }
    if (this.selectedBox.noBox) {
      DrawSelection(this.selectedBox.noBox.position.x, this.selectedBox.noBox.position.y, "blue");
      return DrawConnection(this.selectedBox, this.selectedBox.noBox, "blue");
    }
  };

}).call(this);
