// Generated by CoffeeScript 1.10.0
(function() {
  var eval_code, inputType, intprtAlert, intprtPrompt, onSwalClick, onSwalInput, promptRegex, replaceRegex, resumeMessage, vars_dict;

  promptRegex = /intprtPrompt\([\s\S]*?\)/;

  replaceRegex = /\"|\'/;

  vars_dict = {};

  inputType = '';

  eval_code = "";

  this.interpreteInterface = function(code, vars) {
    vars_dict = vars;
    eval_code = code;
    return eval(code);
  };

  intprtAlert = function(text_message) {
    return swal({
      title: text_message.toString(),
      animation: "none",
      allowEscapeKey: false
    }).then(onSwalClick);
  };

  intprtPrompt = function(text_message) {
    return swal({
      title: text_message.toString(),
      animation: "none",
      allowEscapeKey: false,
      input: 'textarea',
      showCancelButton: false
    }).then(function(text) {
      return onSwalInput(text);
    });
  };

  onSwalInput = function(input_text) {
    if (isNaN(input_text)) {
      input_text = input_text.replace(/["'-[\]{}()*+?.,\\^$|#\s]/g, "\\$&");
      eval_code = eval_code.replace(promptRegex, "\"" + input_text + "\"");
    } else {
      eval_code = eval_code.replace(promptRegex, input_text);
    }
    eval(eval_code);
    return setTimeout(resumeMessage, 500);
  };

  onSwalClick = function() {
    return setTimeout(resumeMessage, 500);
  };

  resumeMessage = function() {
    return IntWorker.postMessage(['interResponse', vars_dict]);
  };

}).call(this);
