// Generated by CoffeeScript 1.10.0
(function() {
  var inputType, intprtAlert, intprtPrompt, onSwalClick, onSwalInput, promptRegex, resumeMessage, vars_dict;

  promptRegex = /intprtPrompt\([\s\S]*?\)/;

  vars_dict = {};

  inputType = '';

  this.interpreteInterface = function(code, vars) {
    console.log(vars);
    vars_dict = vars;
    return eval(code);
  };

  intprtAlert = function(text) {
    return swal({
      title: text.toString(),
      animation: "none",
      allowEscapeKey: false
    }, onSwalClick);
  };

  intprtPrompt = function(text) {
    return swal({
      title: text.toString(),
      animation: "none",
      allowEscapeKey: false,
      type: "input",
      inputPlaceholder: "Your input here"
    }, onSwalInput);
  };

  onSwalInput = function(input_text) {
    setTimeout(resumeMessage, 700);
    return input_text;
  };

  onSwalClick = function() {
    return setTimeout(resumeMessage, 700);
  };

  resumeMessage = function() {
    return IntWorker.postMessage(['interResponse', vars_dict]);
  };

}).call(this);
