// Generated by CoffeeScript 1.10.0
(function() {
  var workerMessage;

  this.IntWorker = null;

  this.onload = function() {
    this.IntWorker = new Worker("interpreter.js");
    this.IntWorker.postMessage(['init']);
    this.IntWorker.onmessage = workerMessage;
    InitForms();
    InitCanvas();
    InitHTML();
    return DrawAllBoxes();
  };

  workerMessage = function(event) {
    switch (event.data[0]) {
      case 'interface':
        return window.interpreteInterface(event.data[1], event.data[2]);
    }
  };

}).call(this);
