// Generated by CoffeeScript 1.10.0
(function() {
  this.saveString = function() {
    var box, file_string, j, len;
    file_string = "";
    for (j = 0, len = boxes.length; j < len; j++) {
      box = boxes[j];
      file_string += box.name + ";";
      file_string += box.text + ";";
      file_string += box.position.x + ";";
      file_string += box.position.y + ";";
      file_string += box.type + ";";
      file_string += box.boxID + ";";
      if (box.yesBox) {
        file_string += box.yesBox.boxID;
      }
      file_string += ";";
      if (box.noBox) {
        file_string += box.noBox.boxID;
      }
      file_string += ";";
      file_string += "|";
    }
    file_string = file_string.slice(0, file_string.length - 1);
    return file_string;
  };

  this.loadString = function(file_string) {
    var box, error, ex, file, i, j, k, l, len, line, ref, ref1, results;
    try {
      file = file_string.split("|");
      for (i = j = 0, ref = file.length; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
        file[i] = file[i].split(";");
      }
      for (k = 0, len = file.length; k < len; k++) {
        line = file[k];
        box = new Box(line[4]);
        box.name = line[0];
        box.setText(line[1]);
        box.position = new Vector(parseInt(line[2]), parseInt(line[3]));
        box.boxID = parseInt(line[5]);
        this.boxes.push(box);
      }
      results = [];
      for (i = l = 0, ref1 = boxes.length; 0 <= ref1 ? l < ref1 : l > ref1; i = 0 <= ref1 ? ++l : --l) {
        if (file[i][6] !== "") {
          boxes[i].yesBox = GetByID(parseInt(file[i][6]));
          console.log(boxes[i].yesBox);
          boxes[i].yesBox.prevBoxes.push(boxes[i]);
        }
        if (file[i][7] !== "") {
          boxes[i].noBox = GetByID(parseInt(file[i][7]));
          results.push(boxes[i].noBox.prevBoxes.push(boxes[i]));
        } else {
          results.push(void 0);
        }
      }
      return results;
    } catch (error) {
      ex = error;
      swal("File corrupted!");
      return console.log(ex);
    }
  };

}).call(this);
